/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as DeveloperConsoleRouteImport } from './routes/developer-console'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IposIndexRouteImport } from './routes/ipos/index'
import { Route as IposIpoIdRouteImport } from './routes/ipos/$ipoId'

const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperConsoleRoute = DeveloperConsoleRouteImport.update({
  id: '/developer-console',
  path: '/developer-console',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IposIndexRoute = IposIndexRouteImport.update({
  id: '/ipos/',
  path: '/ipos/',
  getParentRoute: () => rootRouteImport,
} as any)
const IposIpoIdRoute = IposIpoIdRouteImport.update({
  id: '/ipos/$ipoId',
  path: '/ipos/$ipoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/dashboard': typeof DashboardRoute
  '/developer-console': typeof DeveloperConsoleRoute
  '/research': typeof ResearchRoute
  '/ipos/$ipoId': typeof IposIpoIdRoute
  '/ipos/': typeof IposIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/dashboard': typeof DashboardRoute
  '/developer-console': typeof DeveloperConsoleRoute
  '/research': typeof ResearchRoute
  '/ipos/$ipoId': typeof IposIpoIdRoute
  '/ipos': typeof IposIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/dashboard': typeof DashboardRoute
  '/developer-console': typeof DeveloperConsoleRoute
  '/research': typeof ResearchRoute
  '/ipos/$ipoId': typeof IposIpoIdRoute
  '/ipos/': typeof IposIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/dashboard'
    | '/developer-console'
    | '/research'
    | '/ipos/$ipoId'
    | '/ipos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/dashboard'
    | '/developer-console'
    | '/research'
    | '/ipos/$ipoId'
    | '/ipos'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/dashboard'
    | '/developer-console'
    | '/research'
    | '/ipos/$ipoId'
    | '/ipos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  DashboardRoute: typeof DashboardRoute
  DeveloperConsoleRoute: typeof DeveloperConsoleRoute
  ResearchRoute: typeof ResearchRoute
  IposIpoIdRoute: typeof IposIpoIdRoute
  IposIndexRoute: typeof IposIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer-console': {
      id: '/developer-console'
      path: '/developer-console'
      fullPath: '/developer-console'
      preLoaderRoute: typeof DeveloperConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipos/': {
      id: '/ipos/'
      path: '/ipos'
      fullPath: '/ipos/'
      preLoaderRoute: typeof IposIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipos/$ipoId': {
      id: '/ipos/$ipoId'
      path: '/ipos/$ipoId'
      fullPath: '/ipos/$ipoId'
      preLoaderRoute: typeof IposIpoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  DashboardRoute: DashboardRoute,
  DeveloperConsoleRoute: DeveloperConsoleRoute,
  ResearchRoute: ResearchRoute,
  IposIpoIdRoute: IposIpoIdRoute,
  IposIndexRoute: IposIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
