import type { CSSProperties } from "react";
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Bell,
  Bookmark,
  Building,
  Building2,
  Calendar,
  Check,
  CheckCheck,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  Clock,
  Database,
  Eye,
  FileClock,
  FileText,
  Flame,
  Gem,
  GitCompare,
  Info,
  Layers,
  ListOrdered,
  Lock,
  type LucideIcon,
  MessageCircle,
  Minus,
  MinusCircle,
  PieChart,
  Rocket,
  Route,
  Search,
  SearchX,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Sliders,
  Unlock,
  Sparkles,
  Star,
  Target,
  TrendingDown,
  TrendingUp,
  Trophy,
  User,
  UserX,
  Users,
  X,
  XCircle,
  Play,
  Flag,
  Tag,
  Gavel,
  Presentation,
  Plus,
  Crown,
  Menu,
  Moon,
  Sun,
} from "lucide-react";

/**
 * Lucide icon registry — replaces the UI kit's client-only
 * `<i data-lucide>` + `lucide.createIcons()` pattern with SSR-safe
 * `lucide-react` components. Colour is inherited via `currentColor`.
 */

const REGISTRY = {
  sparkles: Sparkles,
  "arrow-right": ArrowRight,
  "arrow-left": ArrowLeft,
  "arrow-up-right": ArrowUpRight,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  rocket: Rocket,
  calendar: Calendar,
  layers: Layers,
  lock: Lock,
  star: Star,
  shield: Shield,
  "shield-check": ShieldCheck,
  "shield-alert": ShieldAlert,
  target: Target,
  search: Search,
  "search-x": SearchX,
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  minus: Minus,
  "minus-circle": MinusCircle,
  bell: Bell,
  bookmark: Bookmark,
  check: Check,
  "check-check": CheckCheck,
  "check-circle-2": CheckCircle2,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  clock: Clock,
  database: Database,
  eye: Eye,
  activity: Activity,
  building: Building,
  "building-2": Building2,
  "file-clock": FileClock,
  "file-text": FileText,
  flame: Flame,
  gem: Gem,
  "git-compare": GitCompare,
  info: Info,
  "list-ordered": ListOrdered,
  "message-circle": MessageCircle,
  "pie-chart": PieChart,
  route: Route,
  sliders: Sliders,
  trophy: Trophy,
  unlock: Unlock,
  user: User,
  "user-x": UserX,
  users: Users,
  x: X,
  "x-circle": XCircle,
  play: Play,
  flag: Flag,
  tag: Tag,
  gavel: Gavel,
  presentation: Presentation,
  plus: Plus,
  crown: Crown,
  menu: Menu,
  moon: Moon,
  sun: Sun,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof REGISTRY;

export interface IconProps {
  name: IconName;
  size?: number;
  color?: string;
  style?: CSSProperties;
}

export function Icon({ name, size = 18, color, style }: IconProps) {
  const Glyph = REGISTRY[name];
  return (
    <span style={{ display: "inline-flex", lineHeight: 0, color, ...style }}>
      <Glyph size={size} strokeWidth={2} aria-hidden="true" />
    </span>
  );
}
