#!/usr/bin/env node
// Generates the combined Netquity vendor mirror migration SQL from _ref/Sample/*.mdb via
// mdbtools, plus the hand-authored nq_ops.del_sec operational table, and (when writing to
// the canonical migration path) appends or updates the manifest row in
// deploy/database/migrations.contract.json. If the row already exists and its schemas/tables
// differ from what was just generated, it is updated in place; if that update would remove a
// previously-listed table, the script fails closed unless --allow-table-removal is passed.
//
// Usage:
//   node scripts/netquity-mirror/generate-schema.mjs [--source-dir <dir>] [--out <path>]
//     [--allow-table-removal]

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  CANONICAL_MIGRATION_FILE,
  fail,
  installFailSafetyNet,
  listMdbFiles,
  OPS_SCHEMA_NAME,
  parseArgs,
  preflightMdbTools,
  progress,
  readMdbTableNames,
  resolveSourceDir,
  runMdbSchema,
  scanForbiddenSql
} from "./lib.mjs";

// fail() throws (rather than process.exit()-ing directly) so that any try/finally cleanup up the
// call stack still runs; this script has no such cleanup (no tmpdir is ever created), so this is
// purely a safety net restoring fail()'s old "clean message, exit 1" behavior instead of an
// uncaught-exception stack trace dump. See lib.mjs installFailSafetyNet / NetquityFailError.
installFailSafetyNet();

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const PK_DEMOTIONS_PATH = resolve(SCRIPT_DIR, "pk-demotions.json");

const BANNER_AND_ENCODING_PREFIX = `-- ----------------------------------------------------------
-- MDB Tools - A library for reading MS Access database files
-- Copyright (C) 2000-2011 Brian Bruns and others.
-- Files in libmdb are licensed under LGPL and the utilities under
-- the GPL, see COPYING.LIB and COPYING files respectively.
-- Check out http://mdbtools.sourceforge.net
-- ----------------------------------------------------------

SET client_encoding = 'UTF-8';

`;

const SQL_HEADER = `-- Netquity vendor Access-mdb -> PostgreSQL 1:1 mirror schema.
-- Generated by scripts/netquity-mirror/generate-schema.mjs from _ref/Sample/*.mdb via mdbtools.
-- Each source .mdb maps to one nq_<file> schema; nq_ops.del_sec mirrors the vendor
-- del_sec_*.dat delisted-securities feed. Structure only -- no rows are loaded by this file.
-- rights posture: default_deny (licensed vendor raw data; market_data false)
--
-- Deviation 1: inline "NOT NULL" on column definitions is stripped. mdb-schema translates
-- Access's per-field "Required" metadata into NOT NULL, but that metadata is demonstrably not
-- enforced in vendor deliveries: 3 tables across 3 different source .mdb files each contain a
-- real row that violates their own declared NOT NULL. Loading faithfully with those
-- constraints in place rolled back all three tables (0 rows loaded) on the first full load
-- run -- a whole-table failure from advisory metadata, not from real data-integrity work, and
-- the same class of row will recur on future vendor delivery drops (daily incremental
-- updater). Primary-key columns keep NOT NULL implicitly via their PRIMARY KEY constraint
-- (Postgres enforces this regardless of the column's own DDL), so the invariant that actually
-- matters -- no NULL in a key column -- is unaffected; only non-key "Required" advisory
-- metadata is dropped.
--
-- Deviation 2: for the 3 tables above, the offending column turned out to be a member of that
-- table's own documented composite PRIMARY KEY (the exact licensed rows are intentionally kept
-- out of this public migration; pk-demotions.json names only the affected table/key shape) -- so
-- Deviation 1 alone cannot make those
-- rows loadable, because PostgreSQL enforces NOT NULL on every PRIMARY KEY column
-- unconditionally; this is a relational invariant, not a strictness setting. The vendor's own
-- Word dictionary independently documents the same composite key for all 3 tables (so this is
-- not a schema-inference mistake), but the delivered rows violate it. For exactly these 3
-- tables, and only these 3, the documented key is demoted from PRIMARY KEY to a UNIQUE
-- constraint of the same columns: PostgreSQL's default NULLS DISTINCT behavior on UNIQUE
-- constraints approximates Jet/Access's lax NULL-in-key handling (multiple NULLs coexist),
-- while uniqueness is still fully enforced across every fully-non-NULL key combination. This
-- is an explicit, evidence-backed exception register, not a blanket rule -- see
-- scripts/netquity-mirror/pk-demotions.json for the exact schema/table/columns/reason/evidence
-- for each entry; generate-schema.mjs fails hard if an entry's columns drift from the table's
-- actual generated key, or if an entry never matches any generated table.

SET client_encoding = 'UTF-8';

`;

const DEL_SEC_BLOCK = `CREATE SCHEMA IF NOT EXISTS ${OPS_SCHEMA_NAME};

CREATE TABLE IF NOT EXISTS "nq_ops"."del_sec"
 (
	"del_date"			DATE NOT NULL,
	"code"			VARCHAR (10) NOT NULL
);
COMMENT ON TABLE "nq_ops"."del_sec" IS 'Mirrors vendor del_sec_*.dat delisted-securities feed verbatim; codes are kept as text to preserve leading zeros, e.g. 08558.';

-- CREATE INDEXES ...
ALTER TABLE "nq_ops"."del_sec" ADD CONSTRAINT "del_sec_pkey" PRIMARY KEY ("del_date", "code");
`;

const DEL_SEC_TABLE_ENTRY = '"nq_ops"."del_sec"';

// Column-definition lines look like `\t"colname"\t\t\tTYPE [(n)] [NOT NULL],` (trailing comma
// optional on a table's last column). Empirically verified across all 172 source tables (210
// occurrences total): this exact " NOT NULL" token never appears anywhere else in mdb-schema's
// output -- not inside COMMENT ON COLUMN text, not inside an identifier. See the SQL_HEADER
// comment above for why it is stripped.
const INLINE_NOT_NULL_PATTERN = / NOT NULL(?=,?[ \t]*\r?\n)/gu;

const args = parseArgs(process.argv.slice(2), {
  boolean: ["allow-table-removal"],
  string: ["source-dir", "out"]
});

preflightMdbTools();

const pkDemotions = loadPkDemotions(PK_DEMOTIONS_PATH);
const appliedDemotions = new Set();

const sourceDir = resolveSourceDir(args);
const mdbFiles = listMdbFiles(sourceDir);
progress("netquity-schema", `found ${mdbFiles.length} .mdb files in ${sourceDir}`);
progress("netquity-schema", `loaded ${pkDemotions.length} PK demotion(s) from ${PK_DEMOTIONS_PATH}`);

const droppedComments = [];
const fileChunks = [];
const tableEntries = [];
let expectedTableCount = 0;
let strippedNotNullCount = 0;

for (const file of mdbFiles) {
  const rawSql = runMdbSchema(file.absPath, file.schemaName);
  if (!rawSql.startsWith(BANNER_AND_ENCODING_PREFIX)) {
    fail(
      `mdb-schema output for ${file.fileName} did not start with the expected mdbtools banner + client_encoding preamble; refusing to strip blindly (mdbtools version drift?).`
    );
  }
  const body = rawSql.slice(BANNER_AND_ENCODING_PREFIX.length);

  const tableNames = readMdbTableNames(file.absPath);
  expectedTableCount += tableNames.length;
  for (const tableName of tableNames) {
    tableEntries.push(`"${file.schemaName}"."${tableName.toLowerCase()}"`);
  }

  const indexRewritten = body.replace(/^CREATE INDEX "/gmu, 'CREATE INDEX IF NOT EXISTS "');

  const notNullMatches = indexRewritten.match(INLINE_NOT_NULL_PATTERN);
  strippedNotNullCount += notNullMatches ? notNullMatches.length : 0;
  const rewritten = indexRewritten.replace(INLINE_NOT_NULL_PATTERN, "");

  const sanitizedLines = [];
  for (const line of rewritten.split("\n")) {
    if (/^COMMENT ON COLUMN /u.test(line)) {
      droppedComments.push({ file: file.fileName });
      continue;
    }
    sanitizedLines.push(line.trimEnd());
  }
  const sanitized = sanitizedLines.join("\n");

  const structuralMatches = scanForbiddenSql(sanitized);
  if (structuralMatches.length > 0) {
    fail(
      `Forbidden SQL pattern(s) [${structuralMatches.join(", ")}] found outside a COMMENT ON COLUMN line in ${file.fileName}; refusing to silently mutate structural DDL. Inspect the source table/column names.`
    );
  }

  const demoted = applyPkDemotions(sanitized, file.schemaName, pkDemotions, appliedDemotions);

  fileChunks.push(`CREATE SCHEMA IF NOT EXISTS ${file.schemaName};\n\n${demoted}`);
}

const unappliedDemotions = pkDemotions.filter(
  (demotion) => !appliedDemotions.has(demotionKey(demotion))
);
if (unappliedDemotions.length > 0) {
  fail(
    `pk-demotions.json entries never matched any generated table -- schema/table typo, or the source .mdb is not present: ${unappliedDemotions
      .map((demotion) => `${demotion.schema}.${demotion.table}`)
      .join(", ")}`
  );
}
progress(
  "netquity-schema",
  `applied ${appliedDemotions.size} PK-to-UNIQUE demotion(s) from pk-demotions.json (see SQL_HEADER Deviation 2)`
);

tableEntries.push(DEL_SEC_TABLE_ENTRY);
expectedTableCount += 1;

const finalSql = `${SQL_HEADER}${fileChunks.join("\n")}\n${DEL_SEC_BLOCK}`;

const finalForbidden = scanForbiddenSql(finalSql);
if (finalForbidden.length > 0) {
  fail(`Assembled migration SQL still contains forbidden pattern(s): ${finalForbidden.join(", ")}`);
}

const actualTableCount = countOccurrences(finalSql, /create table if not exists/giu);
const actualSchemaCount = countOccurrences(finalSql, /create schema if not exists/giu);
const expectedSchemaCount = mdbFiles.length + 1;

progress("netquity-schema", `create table if not exists lines: ${actualTableCount} (expected ${expectedTableCount})`);
progress("netquity-schema", `create schema if not exists lines: ${actualSchemaCount} (expected ${expectedSchemaCount})`);

if (actualTableCount !== expectedTableCount) {
  fail(
    `Table count self-assert failed: generated ${actualTableCount} CREATE TABLE lines, expected ${expectedTableCount} (sum of mdb-tables -1 across source files + 1 for nq_ops.del_sec).`
  );
}
if (actualSchemaCount !== expectedSchemaCount) {
  fail(
    `Schema count self-assert failed: generated ${actualSchemaCount} CREATE SCHEMA lines, expected ${expectedSchemaCount} (one per .mdb file + nq_ops).`
  );
}

const outPath = resolve(process.cwd(), args.out ?? CANONICAL_MIGRATION_FILE);
const isCanonicalOutput = resolve(process.cwd(), CANONICAL_MIGRATION_FILE) === outPath;
const manifestPlan = isCanonicalOutput
  ? prepareMigrationManifestEntry(
      {
        file: CANONICAL_MIGRATION_FILE,
        purpose:
          "Create the Netquity vendor 1:1 mirror schemas (one nq_<file> schema per source .mdb) and the nq_ops.del_sec operational table for licensed HK market data raw ingest, structure only, without loading vendor rows, granting external access, or bypassing default-deny rights posture.",
        schemas: [...mdbFiles.map((file) => file.schemaName), OPS_SCHEMA_NAME],
        tables: tableEntries,
        market_data: false,
        default_rights_status: "default_deny"
      },
      args.allowTableRemoval === true
    )
  : null;

writeFileSync(outPath, finalSql);
progress("netquity-schema", `wrote ${outPath} (${finalSql.length} bytes)`);

if (droppedComments.length > 0) {
  progress(
    "netquity-schema",
    `dropped ${droppedComments.length} vendor COMMENT ON COLUMN line(s); the public migration retains structure, not licensed dictionary prose`
  );
} else {
  progress("netquity-schema", "no vendor COMMENT ON COLUMN lines were present");
}

progress(
  "netquity-schema",
  `stripped ${strippedNotNullCount} inline "NOT NULL" occurrence(s) from column definitions (advisory Access "Required" metadata; PK columns remain NOT NULL implicitly via their PRIMARY KEY constraint -- see SQL_HEADER for evidence)`
);

if (isCanonicalOutput) {
  if (manifestPlan.newRaw !== null) {
    writeFileSync(manifestPlan.contractPath, manifestPlan.newRaw);
  }
  progress("netquity-schema", `migrations.contract.json manifest row ${manifestPlan.result}`);
} else {
  progress("netquity-schema", `--out override used (${outPath}); skipped migrations.contract.json manifest update`);
}

console.log(
  JSON.stringify(
    {
      applied_pk_demotion_count: appliedDemotions.size,
      dropped_comment_count: droppedComments.length,
      out_path: outPath,
      schema_count: actualSchemaCount,
      status: "ok",
      stripped_not_null_count: strippedNotNullCount,
      table_count: actualTableCount
    },
    null,
    2
  )
);

function countOccurrences(text, pattern) {
  const matches = text.match(pattern);
  return matches ? matches.length : 0;
}

function loadPkDemotions(path) {
  let parsed;
  try {
    parsed = JSON.parse(readFileSync(path, "utf8"));
  } catch (error) {
    fail(`Failed to read/parse ${path}: ${error instanceof Error ? error.message : String(error)}`);
  }
  if (!Array.isArray(parsed.demotions)) {
    fail(`${path} must have a top-level "demotions" array`);
  }
  parsed.demotions.forEach((demotion, index) => {
    for (const field of ["schema", "table", "columns", "reason", "evidence"]) {
      if (demotion[field] === undefined) {
        fail(`${path} demotions[${index}] is missing required field "${field}"`);
      }
    }
    if (!Array.isArray(demotion.columns) || demotion.columns.length === 0) {
      fail(`${path} demotions[${index}].columns must be a non-empty array`);
    }
  });
  return parsed.demotions;
}

function demotionKey(demotion) {
  return `${demotion.schema}.${demotion.table}`;
}

// Rewrites `ALTER TABLE "<schema>"."<table>" ADD CONSTRAINT "<table>_pkey" PRIMARY KEY (...)`
// to `ADD CONSTRAINT "<table>_key" UNIQUE (...)` for every demotion entry whose schema matches
// this file. Fails hard (does not silently skip) if a demotion's schema matches this file but
// its table/PK line cannot be found, or if the actual generated PK columns differ from the
// manifest's `columns` -- both signal the manifest has drifted from the real vendor schema.
function applyPkDemotions(sql, schemaName, demotions, appliedDemotions) {
  let updated = sql;
  for (const demotion of demotions.filter((entry) => entry.schema === schemaName)) {
    const escapedTable = escapeRegExp(demotion.table);
    const pattern = new RegExp(
      `ALTER TABLE "${escapeRegExp(demotion.schema)}"\\."${escapedTable}" ADD CONSTRAINT "${escapedTable}_pkey" PRIMARY KEY \\(([^)]+)\\);`,
      "u"
    );
    const match = updated.match(pattern);
    if (!match) {
      fail(
        `pk-demotions.json entry ${demotion.schema}.${demotion.table} does not match any generated PRIMARY KEY line in this file (table missing, or has no PK) -- refusing to apply a stale/incorrect demotion.`
      );
    }
    const actualColumns = match[1].split(",").map((part) => part.trim().replace(/^"|"$/gu, ""));
    if (JSON.stringify(actualColumns) !== JSON.stringify(demotion.columns)) {
      fail(
        `pk-demotions.json entry ${demotion.schema}.${demotion.table} columns [${demotion.columns.join(", ")}] do not match the generated PRIMARY KEY columns [${actualColumns.join(", ")}] -- vendor schema drift; refusing to apply a stale demotion silently.`
      );
    }
    const replacement = `ALTER TABLE "${demotion.schema}"."${demotion.table}" ADD CONSTRAINT "${demotion.table}_key" UNIQUE (${match[1]});`;
    updated = updated.replace(pattern, replacement);
    appliedDemotions.add(demotionKey(demotion));
  }
  return updated;
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/gu, "\\$&");
}

// Returns a human-readable outcome string ("appended" | "updated in place" | "unchanged
// (no-op)") for the progress log. Appending uses a precise text splice (proven not to reformat
// any other entry -- see the trailingAnchor check below); updating an existing entry in place
// uses a full JSON.parse + mutate + JSON.stringify(..., null, 2) round-trip, which is only safe
// because that round-trip has been verified byte-stable against this repo's actual
// migrations.contract.json (same 2-space style, same key order in every existing entry), so
// re-stringifying after replacing one array element does not reformat any other entry.
function prepareMigrationManifestEntry(entry, allowTableRemoval) {
  const contractPath = resolve(process.cwd(), "deploy/database/migrations.contract.json");
  const raw = readFileSync(contractPath, "utf8");
  const contract = JSON.parse(raw);

  const existingIndex = contract.migrations.findIndex((migration) => migration.file === entry.file);

  if (existingIndex === -1) {
    const trailingAnchor = '      "default_rights_status": "default_deny"\n    }\n  ]\n}\n';
    if (!raw.endsWith(trailingAnchor)) {
      fail(
        "deploy/database/migrations.contract.json does not end with the expected trailing shape; refusing to append the manifest row programmatically. Add it by hand."
      );
    }

    const indentedEntry = JSON.stringify(entry, null, 2)
      .split("\n")
      .map((line) => `    ${line}`)
      .join("\n");

    const head = raw.slice(0, raw.length - trailingAnchor.length);
    const newRaw = `${head}      "default_rights_status": "default_deny"\n    },\n${indentedEntry}\n  ]\n}\n`;

    // Round-trip parse to confirm the splice produced valid, equivalent-shape JSON before writing.
    const reparsed = JSON.parse(newRaw);
    if (reparsed.migrations.length !== contract.migrations.length + 1) {
      fail("Manifest splice produced an unexpected migrations array length; refusing to write.");
    }

    return { contractPath, newRaw, result: "appended" };
  }

  const existing = contract.migrations[existingIndex];
  const schemasChanged = JSON.stringify(existing.schemas) !== JSON.stringify(entry.schemas);
  const tablesChanged = JSON.stringify(existing.tables) !== JSON.stringify(entry.tables);
  if (!schemasChanged && !tablesChanged) {
    return { contractPath, newRaw: null, result: "unchanged (no-op)" };
  }

  const removedTables = (existing.tables ?? []).filter((table) => !entry.tables.includes(table));
  if (removedTables.length > 0 && !allowTableRemoval) {
    fail(
      `Regenerating the manifest row for ${entry.file} would remove ${removedTables.length} previously-listed table(s): ` +
        `[${removedTables.join(", ")}]. This usually means a source .mdb file or table disappeared. If that is expected ` +
        "(e.g. a vendor table was deliberately dropped from this delivery), re-run with --allow-table-removal."
    );
  }

  contract.migrations[existingIndex] = entry;
  const newRaw = `${JSON.stringify(contract, null, 2)}\n`;

  // Round-trip parse to confirm the rewrite produced valid, equivalent-shape JSON before writing,
  // and that only this one entry actually changed.
  const reparsed = JSON.parse(newRaw);
  if (reparsed.migrations.length !== contract.migrations.length) {
    fail("Manifest in-place update produced an unexpected migrations array length; refusing to write.");
  }

  return {
    contractPath,
    newRaw,
    result: removedTables.length > 0 ? "updated in place (table removal allowed)" : "updated in place"
  };
}
